server.port=8081
app.name=service-2
app.environment=dev
app.version=1.0.0
app.feature.flag=false
app.config.source=properties-file
app.config.use-ssm=true
app.config.ssm.path=/service-2/

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
