// S3 Environment File Module
// Merges parameters and creates .env files in S3
//
// Merge hierarchy (later overrides earlier):
//   1. Common env-wide - defaults for all services in all envs
//   2. Common service-specific - defaults for specific service in all envs
//   3. Environment env-wide - overrides for all services in this env
//   4. Environment service-specific - overrides for specific service in this env

locals {
  // Key mapping: convert parameter paths to environment variable names
  // e.g., "jvm/opts" -> "JAVA_OPTS", "app/log/level" -> "APP_LOG_LEVEL"
  key_mappings = {
    "jvm/opts" = "JAVA_OPTS"
  }

  // Build merged parameters for each service
  service_params = {
    for service in var.services : service => merge(
      // 1. Common env-wide parameters
      var.common_params,
      // 2. Common service-specific parameters (strip service prefix)
      { for k, v in var.common_service_params : trimprefix(k, "${service}/") => v if startswith(k, "${service}/") },
      // 3. Environment env-wide parameters
      var.env_params,
      // 4. Environment service-specific parameters (strip service prefix)
      { for k, v in var.env_service_params : trimprefix(k, "${service}/") => v if startswith(k, "${service}/") }
    )
  }

  // Convert parameter keys to environment variable format
  // Rule: use mapping if exists, otherwise replace "/" with "_" and uppercase
  service_env_vars = {
    for service, params in local.service_params : service => {
      for key, value in params :
      lookup(local.key_mappings, key, upper(replace(key, "/", "_"))) => value
    }
  }

  // Generate .env file content for each service
  env_file_contents = {
    for service in var.services : service => join("\n", concat(
      [
        "# Generated by Terraform",
        "# Environment: ${var.environment}",
        "# Service: ${service}",
        "# Generated at: ${timestamp()}",
        "#",
        "# DO NOT EDIT MANUALLY - Changes will be overwritten",
        ""
      ],
      [
        for key in sort(keys(local.service_env_vars[service])) :
        "${key}=${local.service_env_vars[service][key]}"
      ],
      [""] // trailing newline
    ))
  }
}

// Upload .env files to S3
resource "aws_s3_object" "env_file" {
  for_each = toset(var.services)

  bucket       = var.s3_bucket_id
  key          = "${each.value}.env"
  content      = local.env_file_contents[each.value]
  content_type = "text/plain"

  tags = {
    ManagedBy   = "terraform"
    Environment = var.environment
    Service     = each.value
  }
}

output "env_file_arns" {
  description = "ARNs of the uploaded .env files"
  value       = { for k, v in aws_s3_object.env_file : k => v.arn }
}

output "env_file_keys" {
  description = "S3 keys of the uploaded .env files"
  value       = { for k, v in aws_s3_object.env_file : k => v.key }
}

output "env_file_contents" {
  description = "Contents of the generated .env files (for debugging)"
  value       = local.env_file_contents
  sensitive   = true
}

output "service_env_vars" {
  description = "Environment variables per service (for debugging)"
  value       = local.service_env_vars
  sensitive   = true
}
